# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: npm install   # echo 'init script' # runs during prebuild
    command: | 
      export HMR_HOST=`gp url 3000`
      echo "Revving up..."
      npm run dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - prisma.prisma
    - svelte.svelte-vscode
